Q_and_A = [['Who is the main protagonist of the Harry Potter series?', 
               ['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Draco Malfoy'], 
               'Harry Potter'],
              ['What magical object allows Harry to travel back in time in "Harry Potter and the Prisoner of Azkaban"?', 
               ['Time-Turner', 'Invisibility Cloak', 'Portkey', 'Floo Powder'], 
               'Time-Turner'],
              ['Who is the headmaster of Hogwarts School of Witchcraft and Wizardry?', 
               ['Albus Dumbledore', 'Severus Snape', 'Minerva McGonagall', 'Rubeus Hagrid'], 
               'Albus Dumbledore'],
              ['The Dark Mark is the symbol associated with which dark wizard?', 
               ['Lord Voldemort', 'Gellert Grindelwald', 'Herpo the Foul', 'Bellatrix Lestrange'], 
               'Lord Voldemort'],
              ['In the first book, "Harry Potter and the Philosopher\'s Stone," what creature guards the Philosopher\'s Stone?', 
               ['Fluffy the Three-Headed Dog', 'Norbert the Norwegian Ridgeback', 'Buckbeak the Hippogriff', 'Aragog the Acromantula'], 
               'Fluffy the Three-Headed Dog'],
              ['Which magical subject at Hogwarts is known for its connection to magical creatures?', 
               ['Care of Magical Creatures', 'Divination', 'Transfiguration', 'Charms'], 
               'Care of Magical Creatures'],
              ['What is the name of Harry\'s owl?', 
               ['Hedwig', 'Errol', 'Pigwidgeon', 'Crookshanks'], 
               'Hedwig'],
              ['The magical world is divided into four houses at Hogwarts. Which house does Harry belong to?', 
               ['Gryffindor', 'Slytherin', 'Hufflepuff', 'Ravenclaw'], 
               'Gryffindor'],
              ['What is the primary mode of transportation for wizards and witches in the magical world?', 
               ['Broomsticks', 'Thestral-drawn carriages', 'Portkeys', 'Apparition'], 
               'Broomsticks'],
              ['What is the core of Harry Potter\'s wand?', 
               ['Phoenix feather', 'Dragon heartstring', 'Unicorn hair', 'Veela hair'], 
               'Phoenix feather'],
              ['What magical artifact does not make the owner the Master of Death?', 
               ['Elder Wand', 'Resurrection Stone', 'Invisibility Cloak', 'Philosopher\'s Stone'], 
               'Philosopher\'s Stone'],
              ['Who is known as the Half-Blood Prince in the series?', 
               ['Severus Snape', 'Tom Riddle', 'Sirius Black', 'Remus Lupin'], 
               'Severus Snape'],
              ['The Quidditch World Cup is held every how many years?', 
               ['Four years', 'Six years', 'Eight years', 'Ten years'], 
               'Four years'],
              ['What magical plant is known for its ability to scream when touched?', 
               ['Mandrake', 'Whomping Willow', 'Devil\'s Snare', 'Mimbulus Mimbletonia'], 
               'Mandrake'],
              ['The Triwizard Tournament is a magical competition between wizards from Hogwarts and two other wizarding schools. Name one of the other participating schools.', 
               ['Beauxbatons Academy of Magic', 'Ouagadou Institute', 'Ilvermorny School of Witchcraft and Wizardry', 'Castelobruxo'], 
               'Beauxbatons Academy of Magic']]
